# Generated by Django 6.0.1 on 2026-01-30 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Начата'), ('completed', 'Завершена')], default='started', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('block_number', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('experiment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.experimentsession')),
            ],
            options={
                'unique_together': {('experiment_session', 'block_number')},
            },
        ),
        migrations.CreateModel(
            name='NBackBlockConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_level', models.IntegerField(default=1)),
                ('trials_per_block', models.IntegerField(default=30)),
                ('stimulus_duration', models.IntegerField(default=500)),
                ('fixation_duration', models.IntegerField(default=2000)),
                ('iti_duration', models.IntegerField(default=250)),
                ('stimulus_type', models.CharField(choices=[('letter', 'Буквы'), ('position', 'Позиции'), ('audio', 'Аудио'), ('mixed', 'Смешанные')], default='letter', max_length=50)),
                ('target_stimuli', models.JSONField(blank=True, default=list)),
                ('non_target_stimuli', models.JSONField(blank=True, default=list)),
                ('target_probability', models.FloatField(default=0.3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nback_config', to='testapp.experimentblock')),
            ],
        ),
        migrations.CreateModel(
            name='NBackPerformanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trials', models.IntegerField(default=0)),
                ('total_targets', models.IntegerField(default=0)),
                ('total_non_targets', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('misses', models.IntegerField(default=0)),
                ('false_alarms', models.IntegerField(default=0)),
                ('correct_rejections', models.IntegerField(default=0)),
                ('hit_rate', models.FloatField(default=0.0)),
                ('false_alarm_rate', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('mean_reaction_time_hits', models.FloatField(blank=True, null=True)),
                ('mean_reaction_time_false_alarms', models.FloatField(blank=True, null=True)),
                ('std_reaction_time_hits', models.FloatField(blank=True, null=True)),
                ('std_reaction_time_false_alarms', models.FloatField(blank=True, null=True)),
                ('d_prime', models.FloatField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('experiment_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nback_performance', to='testapp.experimentblock')),
            ],
            options={
                'verbose_name': 'Сводка N-back производительности',
                'verbose_name_plural': 'Сводки N-back производительности',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_id', models.CharField(max_length=100)),
                ('session_number', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('participant_id', 'session_number')},
            },
        ),
        migrations.AddField(
            model_name='experimentsession',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.participant'),
        ),
        migrations.CreateModel(
            name='NBackTrialData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trial_number', models.IntegerField()),
                ('stimulus', models.TextField(blank=True, null=True)),
                ('response', models.CharField(blank=True, max_length=500, null=True)),
                ('correct_response', models.CharField(blank=True, max_length=500, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('reaction_time', models.FloatField(blank=True, null=True)),
                ('client_start_time', models.BigIntegerField()),
                ('client_stimulus_time', models.BigIntegerField(blank=True, null=True)),
                ('client_response_time', models.BigIntegerField(blank=True, null=True)),
                ('client_fixation_time', models.BigIntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('n_level', models.IntegerField(default=1)),
                ('is_target', models.BooleanField(default=False)),
                ('is_false_alarm', models.BooleanField(default=False)),
                ('is_miss', models.BooleanField(default=False)),
                ('is_correct_rejection', models.BooleanField(default=False)),
                ('is_hit', models.BooleanField(default=False)),
                ('stimulus_type', models.CharField(blank=True, choices=[('letter', 'Буква'), ('position', 'Позиция'), ('audio', 'Аудио'), ('visual', 'Визуальный')], max_length=50, null=True)),
                ('stimulus_sequence_number', models.IntegerField(blank=True, null=True)),
                ('responded', models.BooleanField(default=False)),
                ('pre_stimulus_delay', models.FloatField(blank=True, null=True)),
                ('stimulus_to_fixation_delay', models.FloatField(blank=True, null=True)),
                ('experiment_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.experimentblock')),
            ],
            options={
                'verbose_name': 'Данные N-back триала',
                'verbose_name_plural': 'Данные N-back триалов',
                'db_table': 'nback_trial_data',
                'indexes': [models.Index(fields=['n_level'], name='nback_trial_n_level_762c22_idx'), models.Index(fields=['is_target'], name='nback_trial_is_targ_43eb56_idx'), models.Index(fields=['is_correct'], name='nback_trial_is_corr_d976d0_idx'), models.Index(fields=['responded'], name='nback_trial_respond_012ef4_idx')],
                'unique_together': {('experiment_block', 'trial_number')},
            },
        ),
        migrations.CreateModel(
            name='TrialData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trial_number', models.IntegerField()),
                ('stimulus', models.TextField(blank=True, null=True)),
                ('response', models.CharField(blank=True, max_length=500, null=True)),
                ('correct_response', models.CharField(blank=True, max_length=500, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('reaction_time', models.FloatField(blank=True, null=True)),
                ('client_start_time', models.BigIntegerField()),
                ('client_stimulus_time', models.BigIntegerField(blank=True, null=True)),
                ('client_response_time', models.BigIntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('experiment_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.experimentblock')),
            ],
            options={
                'unique_together': {('experiment_block', 'trial_number')},
            },
        ),
    ]
