# Generated by Django 6.0.1 on 2026-03-03 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoNoGoTrialData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trial_number', models.IntegerField()),
                ('level', models.IntegerField()),
                ('category_index', models.IntegerField()),
                ('category_name', models.CharField(max_length=200)),
                ('trial_in_category', models.IntegerField()),
                ('stimulus', models.TextField()),
                ('response', models.CharField(blank=True, max_length=10, null=True)),
                ('correct_response', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('is_target', models.BooleanField()),
                ('reaction_time', models.FloatField(blank=True, null=True)),
                ('client_category_time', models.BigIntegerField()),
                ('client_stimulus_time', models.BigIntegerField()),
                ('client_response_time', models.BigIntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('experiment_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.experimentblock')),
            ],
            options={
                'verbose_name': 'Данные Go/NoGo триала',
                'verbose_name_plural': 'Данные Go/NoGo триалов',
                'db_table': 'gonogo_trial_data',
                'indexes': [models.Index(fields=['level'], name='gonogo_tria_level_9c5de6_idx'), models.Index(fields=['is_target'], name='gonogo_tria_is_targ_431436_idx'), models.Index(fields=['is_correct'], name='gonogo_tria_is_corr_06312e_idx')],
                'unique_together': {('experiment_block', 'trial_number')},
            },
        ),
    ]
