# Generated by Django 6.0.1 on 2026-03-04 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_gonogotrialdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireTrialData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trial_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('response_value', models.IntegerField()),
                ('reaction_time', models.FloatField(blank=True, null=True)),
                ('client_time', models.BigIntegerField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('experiment_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.experimentblock')),
            ],
            options={
                'verbose_name': 'Данные опросника',
                'verbose_name_plural': 'Данные опросников',
                'db_table': 'questionnaire_trial_data',
                'indexes': [models.Index(fields=['experiment_block'], name='questionnai_experim_78e240_idx')],
                'unique_together': {('experiment_block', 'trial_number')},
            },
        ),
    ]
