# Generated by Django 6.0.1 on 2026-03-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_questionnairetrialdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbackperformancesummary',
            name='experiment_block',
        ),
        migrations.AlterField(
            model_name='nbacktrialdata',
            name='is_correct_rejection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='nbacktrialdata',
            name='is_false_alarm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='nbacktrialdata',
            name='is_hit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='nbacktrialdata',
            name='is_miss',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='NBackBlockConfig',
        ),
        migrations.DeleteModel(
            name='NBackPerformanceSummary',
        ),
    ]
