# Generated by Django 6.0.1 on 2026-03-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_fix_bool_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialdata',
            name='client_fixation_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
