# Generated by Django 6.0.1 on 2026-06-09 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_participant_age_participant_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='specialization',
            field=models.CharField(blank=True, choices=[('IT', 'Программирование / IT'), ('PSY', 'Психология'), ('BIO', 'Биология'), ('MED', 'Медицина'), ('ENG', 'Инженерия'), ('MATH', 'Математика'), ('PHY', 'Физика'), ('LING', 'Лингвистика'), ('ECO', 'Экономика'), ('DES', 'Дизайн'), ('OTHER', 'Другое')], max_length=10, null=True, verbose_name='Специализация / направление подготовки'),
        ),
        migrations.CreateModel(
            name='FatigueRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='Уровень усталости от 1 до 100')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('experiment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.experimentsession')),
            ],
        ),
    ]
