# Generated by Django 6.0.1 on 2026-06-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_participant_specialization_fatiguerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbacktrialdata',
            name='client_start_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
