# Generated by Django 6.0.1 on 2026-10-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_nbacktrialdata_client_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_school_student',
            field=models.BooleanField(default=False, verbose_name='Школьник'),
        ),
        migrations.AddField(
            model_name='participant',
            name='school_class',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='specialization',
            field=models.CharField(blank=True, choices=[('IT', 'Программирование / IT'), ('PSY', 'Психология'), ('BIO', 'Биология'), ('MED', 'Медицина'), ('ENG', 'Инженерия'), ('MATH', 'Математика'), ('PHY', 'Физика'), ('LING', 'Лингвистика'), ('ECO', 'Экономика'), ('DES', 'Дизайн'), ('OTHER', 'Другое'), ('SOC_ECO', 'Социально-экономический класс'), ('TECH', 'Технический класс'), ('NAT_SCI', 'Естественно-научный класс'), ('UNIV', 'Универсальный класс')], max_length=10, null=True, verbose_name='Специализация / направление подготовки'),
        ),
    ]
